### ISSUE TITLE
Great package with minor issues

### ISSUE THREAD

**Issue by sglvladi** [OSUrobotics/cmvision_3d#1]
Hi there,

This is a brilliant package, but unfortunatelly would not run out of the box. Thus, I would like to report the issues that I dealt with and ask a question on them.

Firstly, in "CMakeLists.txt" there is a required package named "privacy". In my case, I could not find any packages with the specific name, so I just took it off to let cmake complete. 

Continuing, the main problem I discovered with the color_controller.py node is that it uses the attribute "name" (blob.name) of message type Blob, which is not provided by cmvision. I am running Hydro and have installed the up-to-date version of cmvision provided here: http://wiki.ros.org/cmvision. I managed to go around this problem, by creating a new class which essentially appends the "name" attribute to each received blob.

From the documentation I can infer that the package was fully functional when uploaded, so I would like to enquire about the version of cmvision that the package was based on.

Thanks

**Comment by ahubers** [comment]
Thanks for your interest and I appreciate that at least one person is using it! Warms the caverns of my open-source heart. 

In reply to the issues you brought up (what's a ROS package without a few issues?),
1. "privacy" is a package of mine that isn't really external-facing. It must have weaved its way into CmakeLists.txt some how. I don't remember, but if you submit a pull request I'd be happy to accept it with the change.
2. About blob.name. I actually contributed a bit to what I recall to be the current maintained version of cmvision here, appending "name" to the blob message type. Here's the specific commit utexas-bwi/cmvision@f29d33a525ef0c1dcaab9c2a719590a14f26b28a. My ROS knowledge is rusty, but I believe Piyush (the maintainer) said he'd update this to the rosdistro so that new installs of ROS will have the change I made included in cmvision. He may have forgot to do so, or I may just not know how rosdistro works well enough. I can contact him or possibly do it myself. Regardless, the issue should go away if you just instead download the latest version from the linked repository.

Let me know how it goes.

**Comment by sglvladi** [comment]
Hi again and thanks for the quick reply.

 As suggested, I downloaded the latest version and everything runs smoothly now. Once again, let me thank you for your contribution. It is pretty nice package and it's saved us a lot of effort and time.

All the best

**Comment by ahubers** [comment]
Sounds good. If you like, feel free to fork this repo, clone the fork, push the CmakeList changes back up and then submit a pull request. Either that or just let me know what line(s) you removed from CmakeLists.txt and I'll fix the issue. I'll also contact Piyush about adding the latest version of cmvision to the rosdistro.

Thanks again

**Comment by piyushk** [comment]
A new release of cmvision is incoming: https://github.com/ros/rosdistro/pull/7428

**Comment by sglvladi** [comment]
I've just submitted the pull request. Since I am somewhat new to github, I hope I have done it correctly. Let me know if anything else is needed. 

Again, many thanks for the support

**Comment by ahubers** [comment]
Excellent. Thanks for your contribution!
